name: 'Mutating Tic-Tac-Toe'

on:
  push:
    branches:
      - master

jobs:
  run-pitest:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - name: Install maven
        uses: xlui/action-maven-cli@v1.0

      - name: Install dependencies
        run: mvn clean install

      - name: Run pitest
        run: mvn org.pitest:pitest-maven:mutationCoverage
