name: 'Mutating Tic-Tac-Toe'

on:
  push:
    branches:
      - master

jobs:
  run-pitest:
    steps:
      - name: Install maven
        uses: xlui/action-maven-cli@v1.0

      - name: Install dependencies
        uses: mvn clean install

      - name: Run pitest
        uses: mvn org.pitest:pitest-maven:mutationCoverage
